### ISSUE TITLE
Self referencing tables not generating properly

### ISSUE THREAD

**Issue by diptip09** [rxweb/RxWebCore#10]
My application has many self referencing tables. Ex. There is a Component Table having a column ParentComponentId which is foreign key column referencing Primary key of same table. Model class of such tables are created with virtual property as below:
#region Component Annotations

        [ForeignKey(nameof(ParentComponentId))]
        [InverseProperty(nameof(PrintLynxx.Models.Main.Component.Components))]
		#endregion Component Annotations

        public virtual Component Component { get; set; }
 which throws error "membernames cannot be same as their enclosing type"

**Comment by ajayojha** [comment]
@diptip09 This feature has been included in our new release of CLI, please update your project package.
