### ISSUE TITLE
Two tables with multiple relations

### ISSUE THREAD

**Issue by diptip09** [rxweb/RxWebCore#13]
Attachments
![Table](https://user-images.githubusercontent.com/62141853/77393045-49f38300-6dc2-11ea-8649-4f2e7c2c03ba.PNG)
![FK1](https://user-images.githubusercontent.com/62141853/77393068-58419f00-6dc2-11ea-94fc-afaecef29598.PNG)
![FK2](https://user-images.githubusercontent.com/62141853/77393069-58da3580-6dc2-11ea-9139-a57cf3460dc1.PNG)
[ModelClass.txt](https://github.com/rxweb/RxWebCore/files/4373443/ModelClass.txt)
![specspecitemmappings table](https://user-images.githubusercontent.com/62141853/77393371-e74eb700-6dc2-11ea-8fa8-633925c55691.PNG)

CompositeSpecItems table has relations with specspecitemmappings table. with two key combinations. (See attachments for further details)

### Further technical details
- ASP.NET Core version 3.1.1
- Include the output of `dotnet --info` Error: Duplicate RelationshipTableAttribue attribute
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version VS2019

**Comment by ajayojha** [comment]
@diptip09 Thanks for sharing the detailed information. The issue has been fixed in our new 1.1.9 release. Please update the same.
