### ISSUE TITLE
Error while Compiling Domain Controller

### ISSUE THREAD

**Issue by diptip09** [rxweb/RxWebCore#16]
Hello Sir, 
One of my team member is having issue compiling Domain Controller. Please see attachments. Updated version of rxwebcore is 1.1.8.

![Untitled1](https://user-images.githubusercontent.com/62141853/77909198-8cc5c700-72aa-11ea-8786-8c541cd471cc.png)
![Untitled2](https://user-images.githubusercontent.com/62141853/77909201-8e8f8a80-72aa-11ea-9eff-2a65cd93d853.png)

**Comment by ajayojha** [comment]
@diptip09 Thanks, this will be fixed in next release.

**Comment by ajayojha** [comment]
@diptip09  The issue has been fixed in 1.1.9 release of CLI.
