### ISSUE TITLE
Update Method is not working

### ISSUE THREAD

**Issue by rachanachag** [rxweb/RxWebCore#17]
While using method for update it's giving error that "Methos Not allowed"(As per screenshot).

![image](https://user-images.githubusercontent.com/46072385/77992900-a74c7e80-7344-11ea-81fb-5502d08e8e90.png)

**Comment by ajayojha** [comment]
@rachanachag Please share enough information to track down the issue.

**Comment by rachanachag** [comment]
I have put "Allowanonymous" on the controller. Post, Get method is working just fine. But when I use the "Put" Method it gives me runtime error **405** as its shown in the screenshot above.

**Comment by ajayojha** [comment]
@rachanachag I would suggest, please pass the authorization header before making a request.

**Comment by rachanachag** [comment]
Ok Thank you so much.it's working with passing tokens but without passing token I can use Post call not patch call
