### ISSUE TITLE
Swagger is not working.

### ISSUE THREAD

**Issue by hinalborad** [rxweb/RxWebCore#18]
swagger is not working in new version (1.1.8) of rxwebcore.
It was running properly in older version, but in newer version i'm not able to call any request.

**Comment by ajayojha** [comment]
@hinalborad Please share enough information to track down the issue.

**Comment by hinalborad** [comment]
When I use swagger for a GET call it is working fine, but when I use PUT (Update) and POST call in swagger to test, it keeps loading just like below screen shot.
I have added PATCH method in code, but there is no patch method in swagger.

![swagger](https://user-images.githubusercontent.com/16860739/78111687-a84fdf80-741a-11ea-86ee-202f70450486.PNG)

**Comment by ajayojha** [comment]
@hinalborad put a breakpoint on the server-side and check that is the request is reaching the server API or not.

**Comment by hinalborad** [comment]
@ajayojha But I'm not able to pass JSON and Execute button is not displaying as well.

**Comment by diptip09** [comment]
I am also facing similar issue. May be because it is taking lot of time to load Example Value | Schema field. My database tables have very complex table relationships

**Comment by ajayojha** [comment]
To drill down the actual issue, I would suggest please check the database process time as well as web server process time

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajayojha** [comment]
I am closing this ticket as not further action required from my end.

**Comment by diptip09** [comment]
I believe there is problem in generating Example Value of different requests. See Attachments. Hence swagger is slow in performance.

[VendorBackgroundsModelclass.txt](https://github.com/rxweb/RxWebCore/files/4585744/VendorBackgroundsModelclass.txt)
[ExampleValueForVendorBackground.txt](https://github.com/rxweb/RxWebCore/files/4585746/ExampleValueForVendorBackground.txt)
