### ISSUE TITLE
One table having two FK relation with another table on same PK column

### ISSUE THREAD

**Issue by diptip09** [rxweb/RxWebCore#19]
Table relation are not generating properly.
while login throwing erro.
"Unable to determine the relationship represented by navigation property 'AbilityScopeStepTeam.Right1' of type 'Right'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'."
-Attachments-------------------------------------------------------------------------------------------------

[AbilityScopeStepTeam.txt](https://github.com/rxweb/RxWebCore/files/4462234/AbilityScopeStepTeam.txt)
[Right.txt](https://github.com/rxweb/RxWebCore/files/4462235/Right.txt)
[TableScript.txt](https://github.com/rxweb/RxWebCore/files/4462236/TableScript.txt)

**Comment by diptip09** [comment]
[TableScript.txt](https://github.com/rxweb/RxWebCore/files/4508133/TableScript.txt)

**Comment by ajayojha** [comment]
@diptip09 the provided table script and the attach model information is incorrect, please check again in your project. I did run the script and check the generated code. All looks good.

can you please check at your end.
Here is the generated code : 
```c#
[Table("AbilityScopeStepTeams",Schema="dbo")]
    public partial class AbilityScopeStepTeam
    {
		#region AbilityId Annotations

        [CompositeKey]
		#endregion AbilityId Annotations

        public int AbilityId { get; set; }

		#region ScopeId Annotations

        [CompositeKey]
		#endregion ScopeId Annotations

        public byte ScopeId { get; set; }

		#region StepId Annotations

        [CompositeKey]
		#endregion StepId Annotations

        public int StepId { get; set; }

		#region TeamRightId Annotations

        [RelationshipTableAttribue("Rights","dbo","","TeamRightId")]
		#endregion TeamRightId Annotations

        public int TeamRightId { get; set; }

		#region RightId Annotations

        [RelationshipTableAttribue("Rights","dbo","","RightId")]
		#endregion RightId Annotations

        public int RightId { get; set; }

		#region StatusTypeId Annotations

        [Required]
		#endregion StatusTypeId Annotations

        public byte StatusTypeId { get; set; }

		#region Right Annotations

        [ForeignKey(nameof(RightId))]
        [InverseProperty(nameof(NewProjectSolution.Models.Main.Right.AbilityScopeStepTeams))]
		#endregion Right Annotations

        public virtual Right Right { get; set; }

		#region Right1 Annotations

        [ForeignKey(nameof(TeamRightId))]
        [InverseProperty(nameof(NewProjectSolution.Models.Main.Right.AbilityScopeStepTeams1))]
		#endregion Right1 Annotations

        public virtual Right Right1 { get; set; }


        public AbilityScopeStepTeam()
        {
        }
	}
```

**Comment by diptip09** [comment]
Hello Sir,
AbilityScopeStepTeams Table has relationship with other tables too but I have not included those relations here. Because I believe the issue is due to below generated part in model of AbilityScopeStepTeams table:

[ForeignKey(nameof(TeamRightId))]
        [InverseProperty(nameof(NewProjectSolution.Models.Main.Right.AbilityScopeStepTeams1))]
		#endregion Right1 Annotations

        public virtual Right Right1 { get; set; }

**Comment by diptip09** [comment]
while login throwing erro.
"Unable to determine the relationship represented by navigation property 'AbilityScopeStepTeam.Right1' of type 'Right'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'."

**Comment by ajayojha** [comment]
You can opt anyone below mentioned approach :

Remove the reference and whatever configuration you have provided here the same try in your project and reproduce the issue.

Second option: please provide me the all reference table information.

I would suggest please try first approach and update here. Would be great if you provide dummy data script for both of the table

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
