### ISSUE TITLE
SQL Datatype tinyint is not supported

### ISSUE THREAD

**Issue by diptip09** [rxweb/RxWebCore#20]
SQL Datatype tinyint is not supported.
for tinyint columns, byte data type is being used in model generation

**Comment by ajayojha** [comment]
@diptip09 The ```Byte``` data type is correct, please refer to this documentation: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-data-type-mappings

I am closing this ticket as there is no further action required on this ticket.
