### ISSUE TITLE
if same user login in two different systems and if user logs out from one system then second system does not work

### ISSUE THREAD

**Issue by bharat0249** [rxweb/RxWebCore#23]
### Describe the bug
if same user login in two different systems and if user logs out from one system then second system does not work

### To Reproduce

open chrome and login with the user

open Firefox and login with the same user

now log out from Firefox and try to operate anything in chrome, it will give errors in console

**Comment by ajayojha** [comment]
it's a feature that the user can able to access the application from anyone logged in the browser. if there is any error which is coming on the client side then I would suggest, please handle the same.
