### ISSUE TITLE
Unable to access api via postman

### ISSUE THREAD

**Issue by pratik-mistry** [rxweb/RxWebCore#3]
I tried following the instructions as given on https://rxweb.io/rx-web-core to create a new project. However, when I try to test the authentication post API using postman, it is unable to resolve the url.

The project builds successfully and is in 'Debugging' state.

Below is screenshot of error I get:
![rxweb io-postman-error](https://user-images.githubusercontent.com/59285107/71573000-b5052480-2b07-11ea-8667-389fc9c360f9.png)

**Comment by pratik-mistry** [comment]
Update:

I tried creating a get method in AuthenticationController and it seems to be working fine in browser:

![image](https://user-images.githubusercontent.com/59285107/71573150-5ab89380-2b08-11ea-9272-9e752c2a68c2.png)

But unable to access this method in postman.

**Comment by ajayojha** [comment]
@pratik-mistry Thanks for reporting this. You have to `OFF` `SSL certificate verification` through the postman settings. 
Please follow the below steps
1. Click on `File` Menu Item
2. Click on `Setting` Sub Menu Item
3. `OFF` the `SSL certificate verification`. below is the screenshot.

![image](https://user-images.githubusercontent.com/20392302/71653339-c2adea80-2d51-11ea-9832-14364ab2aad8.png)


I am closing this ticket if still issue persist you can reopen this ticket.
