### ISSUE TITLE
While using DBContextManager in rxwebcore for using Transaction for relational save Error 

### ISSUE THREAD

**Issue by varsharoberoi** [rxweb/RxWebCore#5]
Right now I solved problem by using AutoTransactionsEnabled false.
Following code:
Uow.Context.Database.AutoTransactionsEnabled = false;
var result = await DbContextManager.BeginTransactionAsync(this.Uow);
using (result)
{
try
{
await Uow.RegisterNewAsync(entity.Student);
Uow.Context.SaveChanges();
await Uow.RegisterNewAsync(entity);
Uow.Context.SaveChanges();
await result.CommitAsync();
}
catch(Exception e)
{
Console.WriteLine(e.Message);
await result.RollbackAsync();
}
}
 Uow.Context.Database.AutoTransactionsEnabled = true;

If it can be included in DbContextManager it will be more good.

**Comment by ajayojha** [comment]
Thanks @varsharoberoi for this ticket. As internally we are using the UseTransaction and BeginTransaction Method so we don't need to accommodate ```AutoTransactionsEnabled``` in the lib. Instead of the result object, you can directly use the ```CommitAsync``` method of DbContextManager.

**Comment by ajayojha** [comment]
I am closing this ticket as no further action required on this. It's good you have shared your inputs. Keep continuing the same :).
