### ISSUE TITLE
Entity Models with composite primary key

### ISSUE THREAD

**Issue by diptip09** [rxweb/RxWebCore#6]
If table has composite primary key then it is throwing error "Entity type <Entity Name> has composite primary key defined with data annotations. To set composite primary key, use fluent API."

**Comment by ajayojha** [comment]
@diptip09  I have released the new package of cli, please update the same as well as you have to update our ```RxWeb.Core.Data``` package version of ```3.0.2-preview2```. If you face any issue please create a new ticket or reopen this ticket.
