### ISSUE TITLE
Two columns with Foreign key relation with same table 

### ISSUE THREAD

**Issue by diptip09** [rxweb/RxWebCore#7]
In our project, for some tables, we need to create two columns LoginUserId and ActingUserId in single table. These two columns has foreign key relation with with User table. While creating model class inverse property relations are not creating.

**Comment by ajayojha** [comment]
@diptip09 Please share the model information(Primary and Foreign Key Model) where inverse property relations are not generated.

**Comment by diptip09** [comment]
Hello Sir,
 The model class is attached here in text format. Note: All CompanyId, DepartmentId, UserId Columns refer to UserId Column of User Table. There is a MemberType Column in User Table which can have values C,D,U  for Company, Department, User resp.
[Job.txt](https://github.com/rxweb/RxWebCore/files/4347206/Job.txt)

**Comment by ajayojha** [comment]
@diptip09 Then mentioned properties are not exits in the provided job.txt file.

**Comment by diptip09** [comment]
I tried to described them in brief. Sorry for incomplete information.
The Attribute list is as below:
BuyerCompanyId, VendorCompanyId, BuyerDepartmentId, VendorDepartmentId, OriginatingDepartmentId, BuyerUserId, VendorUserId

**Comment by ajayojha** [comment]
Thanks @diptip09 for the quick response. The issue has been resolved in the new release, please update the project package.
