### ISSUE TITLE
Enum generation using entries in Application Objects

### ISSUE THREAD

**Issue by diptip09** [rxweb/RxWebCore#8]
In ApplicationObjectTypes we have done an entry as ApplicationObjectTypeId=1, ApplicationObjectTypeName="Status Type" and IsActive=1. Two enums are being created one with space "Status Type" and another without space "StatusType". Note we also have one table which holds data of status type as we want to display status type in multilingual.

**Comment by ajayojha** [comment]
@diptip09 Please share the table data of ApplicationObject and ApplicationObjectType with respect to `Status Type`

**Comment by diptip09** [comment]
**Data in ApplicationObjectTypes Table:**
ApplicationObjectTypeId	ApplicationObjectTypeName	StatusId
1	Status Type	1
2	Shipment History Status	1
3	Currency Format MaskType	1
**Data in ApplicationObjects Table:**
ApplicationObjectId	ApplicationObjectTypeId	ApplicationObjectName	StatusId
1	1	Active	1
2	1	Pending	1
3	1	InActive	1
4	2	Add	1
5	2	Edit	1
6	2	Delete	1
7	3	User Default	1
8	3	ISO	1

Note: Other Enums are being generated properly only Status Type has issue.

**Comment by ajayojha** [comment]
Thanks, @diptip09, I have released the new package, Please update rxwebcore CLIwith the version of 1.1.8 .
