### ISSUE TITLE
New Feature: Scope based role rights

### ISSUE THREAD

**Issue by diptip09** [rxweb/RxWebCore#9]
New Feature Request: Scope based role rights

My application provides platform for different printing companies to get deals with companies providing printing contracts.
There are three type of users Admin, Buyers(who issue printing contracts), Vendors(who provide printing services).
Scenario 1: Admin user can access his/her own organization directory and also can change contact information for users.
            Admin user can access other companies(Buyer or Vendor) but cannot change contact information for users in the companies
Scenario 2: Buyer user can access his/her own "Job Defaults and Preferences" and can edit template group and templates under the group
            Admin user can access "Job Defaults and Preferences" of a buyer company but cannot edit template group and templates under the group
Scenario 3: Buyer user can access all the tabs of Jobs within their own company.
            Admin user can access only few tabs of Jobs of a buyer company.

**Comment by ajayojha** [comment]
@diptip09  Please share the detailed case and highlight the current feature limitation.

**Comment by ajayojha** [comment]
I am closing this ticket as no further update here, whenever you have information please create a new ticket with detailed information.
